{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.6.0-alpha05.aar",
          "url": "activity-1.6.0-alpha05.aar",
          "size": 109454,
          "sha512": "1afb29a1c347bb3cca91c483bece8907e2308980285b68552afef01750fb85c98422e462a6709ecfcafe35d194b5fe4f2e14637fa2030e329caf8aed49128270",
          "sha256": "4dc7a1c955a22cd36d71b31877b18b112bb8bb9b8ebf29cc5928dc4f634df342",
          "sha1": "ea18e928fd25d062002c7e7a9dfc60ca8615f7ad",
          "md5": "2ff136b4c02dbb6149ce0be7b7fa4b83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.6.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.6.0-alpha05.aar",
          "url": "activity-1.6.0-alpha05.aar",
          "size": 109454,
          "sha512": "1afb29a1c347bb3cca91c483bece8907e2308980285b68552afef01750fb85c98422e462a6709ecfcafe35d194b5fe4f2e14637fa2030e329caf8aed49128270",
          "sha256": "4dc7a1c955a22cd36d71b31877b18b112bb8bb9b8ebf29cc5928dc4f634df342",
          "sha1": "ea18e928fd25d062002c7e7a9dfc60ca8615f7ad",
          "md5": "2ff136b4c02dbb6149ce0be7b7fa4b83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.6.0-alpha05-sources.jar",
          "url": "activity-1.6.0-alpha05-sources.jar",
          "size": 43347,
          "sha512": "797a3e5fbccd7d251afe013dea502b543cf491a53a79ca9e43d6bc18d0a7c4e3ecc05d39b7691ac06e1f37acd58a451d9f543af05c27f69a0c992731bbb86d8c",
          "sha256": "c2c7bb7f55c795e3698bc1f38ff42faf4abcc883c3e8c074f161c162005406c1",
          "sha1": "aeaf44649711ef2abc9ccb26c37c6cdb249c48c6",
          "md5": "a8f93be7df6c0fa6bb06b993df27da59"
        }
      ]
    }
  ]
}