{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-ktx",
    "version": "1.9.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.9.0-alpha05.aar",
          "url": "core-ktx-1.9.0-alpha05.aar",
          "size": 178509,
          "sha512": "7c913d2befbd4e966c1b42f3017fac976c081aa367ffb1688358a361765fdeb452097e2cf00bde604b2a53d423fe30caa78c5110391d16d61b4b2a88566db0b9",
          "sha256": "a5a43b2b4019c9c1d2494995a67a8c7560fe9b0181bb1379ac9ae169ca4552a6",
          "sha1": "87c57cd25621ce4760c96242e574d31eb8e8ce4f",
          "md5": "31d56b03f88f6cc55d12a3d80d1e6fad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.9.0-alpha05.aar",
          "url": "core-ktx-1.9.0-alpha05.aar",
          "size": 178509,
          "sha512": "7c913d2befbd4e966c1b42f3017fac976c081aa367ffb1688358a361765fdeb452097e2cf00bde604b2a53d423fe30caa78c5110391d16d61b4b2a88566db0b9",
          "sha256": "a5a43b2b4019c9c1d2494995a67a8c7560fe9b0181bb1379ac9ae169ca4552a6",
          "sha1": "87c57cd25621ce4760c96242e574d31eb8e8ce4f",
          "md5": "31d56b03f88f6cc55d12a3d80d1e6fad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ktx-1.9.0-alpha05-sources.jar",
          "url": "core-ktx-1.9.0-alpha05-sources.jar",
          "size": 69181,
          "sha512": "425b2585f43cee4a6c0393b5f14810eb69b191c44ed8e16398dc097c6c60e83894457551060a77e690bbdffed2954b15218d24328a398bde399cd9b9159be453",
          "sha256": "c8abbed6897d1d19039b911e45369e433a7b27f62aa0f5276e0b761a1e05628a",
          "sha1": "3850f60ae5c85d51335279f163e90163587e2bef",
          "md5": "32f0f92b26f7b7295fccfb30294b7ff2"
        }
      ]
    }
  ]
}