{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-rc01.aar",
          "url": "lifecycle-runtime-2.5.0-rc01.aar",
          "size": 12293,
          "sha512": "4c37b385f747a4c90cfc3b9441c88b1c9703aa9badf8634750b8005e0943cad48c12946f40ae8f94690054509e4c8df5ba41158efb76be261124cd86ce77df71",
          "sha256": "120926e11de9721f3e29ec1eaed97e56d68ae54520cc9d2ee4875d50082179cb",
          "sha1": "6eeed748c7481c47474d574f5fbb9209f530b2a4",
          "md5": "46161e294048ef2e67260a483cee6a32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-rc01.aar",
          "url": "lifecycle-runtime-2.5.0-rc01.aar",
          "size": 12293,
          "sha512": "4c37b385f747a4c90cfc3b9441c88b1c9703aa9badf8634750b8005e0943cad48c12946f40ae8f94690054509e4c8df5ba41158efb76be261124cd86ce77df71",
          "sha256": "120926e11de9721f3e29ec1eaed97e56d68ae54520cc9d2ee4875d50082179cb",
          "sha1": "6eeed748c7481c47474d574f5fbb9209f530b2a4",
          "md5": "46161e294048ef2e67260a483cee6a32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-rc01-sources.jar",
          "url": "lifecycle-runtime-2.5.0-rc01-sources.jar",
          "size": 8970,
          "sha512": "2009c123e8c19a76eb578ab4a999257a8a815e0f576678921cb327ace677502a07c117cd74a3d88e9cc901591f3e993420a60fc7177abe2e3b08532eddb5a4cf",
          "sha256": "7dd944be47d1245d17aae7cc656880f1d91695501955da5256c8659c6964e656",
          "sha1": "0d255b447102736e536a28b97671c6a736c801b7",
          "md5": "bc3ece2ea0121fea9bc2ba8334f1e80e"
        }
      ]
    }
  ]
}