{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-retention-proto",
    "version": "30.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.0.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.0.jar",
          "size": 39328,
          "sha512": "5ae0742ae604e7e88dfb0066ba65e3903d3ce4c0bacdac45a1f2fd8094b45143cf86b76a5956bef837579385d0bef968605a53bfb10e5391235a33c6e3ed8245",
          "sha256": "422e0e98aae177aaabc722f8edbbe1ea3ab6ee3302f7b4259eeb992c92360123",
          "sha1": "3d07978955ee5e98d1d06402752a4a2685b06c6a",
          "md5": "98a8c1180c9a7e3b17f299e35bb64ad2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.0.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.0.jar",
          "size": 39328,
          "sha512": "5ae0742ae604e7e88dfb0066ba65e3903d3ce4c0bacdac45a1f2fd8094b45143cf86b76a5956bef837579385d0bef968605a53bfb10e5391235a33c6e3ed8245",
          "sha256": "422e0e98aae177aaabc722f8edbbe1ea3ab6ee3302f7b4259eeb992c92360123",
          "sha1": "3d07978955ee5e98d1d06402752a4a2685b06c6a",
          "md5": "98a8c1180c9a7e3b17f299e35bb64ad2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.0-javadoc.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.0-javadoc.jar",
          "size": 451215,
          "sha512": "6a5341a5b7d4c17eb070c7457582bdb6e1dce000fc9e3947e232ddaabf71b2946cbfae062c37083c8f7e857de837f37c002912744a723aea67ab250d1f8d697c",
          "sha256": "d0b842aeb6e92c21a9253c5329f739a12965d19b4675176b1686a626040e44c7",
          "sha1": "e7165d632f514b8f109e3e85ea303b2c74b38128",
          "md5": "269719cfa740bf54e65be7c45e347cd1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.0-sources.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.0-sources.jar",
          "size": 16525,
          "sha512": "5beaeb3f1aaada1504979963b6a480aeeea3e24db62df560e270bf040b5560d807f9521fb5a486d40702f73e9ac68de34b9cda3b3f8f9da6cfbaca6a37475367",
          "sha256": "4e6f02e7e99c5412ca85269ba1b3959f4e2b80276a3eb02e2131bb9879eb8466",
          "sha1": "f7fc807527a7442a4c4d9e2f19eabb4661035626",
          "md5": "24edf13122e1ecae4fa02b71b9eb4600"
        }
      ]
    }
  ]
}
