{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.4.0.aar",
          "url": "appcompat-resources-1.4.0.aar",
          "size": 67071,
          "sha512": "17b709b7519ee76915b2fd0b7ef0585a5147d78e2a0a9dda316d62317afda85668b766d30ad8b15b1a4ec86379614f2ee6aa699fb3fe02799702e7d3e0a28ca6",
          "sha256": "433012ea1ffb7ceb22e5cd2dd7eb9b30a23fd61fe79391cf9d75b81cd4f9eb69",
          "sha1": "47cd4cd29664c87234617e3649f741187a7dc9bd",
          "md5": "15105fcffc4e2eeb0d0fdedc6b8db515"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.4.0.aar",
          "url": "appcompat-resources-1.4.0.aar",
          "size": 67071,
          "sha512": "17b709b7519ee76915b2fd0b7ef0585a5147d78e2a0a9dda316d62317afda85668b766d30ad8b15b1a4ec86379614f2ee6aa699fb3fe02799702e7d3e0a28ca6",
          "sha256": "433012ea1ffb7ceb22e5cd2dd7eb9b30a23fd61fe79391cf9d75b81cd4f9eb69",
          "sha1": "47cd4cd29664c87234617e3649f741187a7dc9bd",
          "md5": "15105fcffc4e2eeb0d0fdedc6b8db515"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-resources-1.4.0-sources.jar",
          "url": "appcompat-resources-1.4.0-sources.jar",
          "size": 40855,
          "sha512": "6dbc472b68da1cf1e7c08973d9f796881ca59ab21bc922580d3ca8b07b206a50e07d9751cfc802d580cff5d08aa2f7dd84061cd090397328d14f090d2bc184bf",
          "sha256": "014980c366a1755d486e4cde2ea616cc2074963c5f48ffcb01dee15dd5f9421d",
          "sha1": "8f78838745a125dea62514f7b4f70e8776a6244e",
          "md5": "4e8141afafcbf7ffe9e19ec02207f2e0"
        }
      ]
    }
  ]
}
