{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint-model",
    "version": "30.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lint-model-30.1.0.jar",
          "url": "lint-model-30.1.0.jar",
          "size": 158181,
          "sha512": "5b5d07041401c6a9b0fa0d5816f8b4ccb8858d2c9500d15968847ef5af166ef0c906acbb6a6478a36bcaf8fbae33677b13bbaf8088a8b98a4861a27f098a3a9e",
          "sha256": "bc2d78d6887a3a984213552a7209d1e76953f8bbdc38ed569243cfadac3df94f",
          "sha1": "1d3236d1e6420c521e5d25c8592e006b71535306",
          "md5": "72df82c779968b64b58d55161da4c237"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lint-model-30.1.0.jar",
          "url": "lint-model-30.1.0.jar",
          "size": 158181,
          "sha512": "5b5d07041401c6a9b0fa0d5816f8b4ccb8858d2c9500d15968847ef5af166ef0c906acbb6a6478a36bcaf8fbae33677b13bbaf8088a8b98a4861a27f098a3a9e",
          "sha256": "bc2d78d6887a3a984213552a7209d1e76953f8bbdc38ed569243cfadac3df94f",
          "sha1": "1d3236d1e6420c521e5d25c8592e006b71535306",
          "md5": "72df82c779968b64b58d55161da4c237"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-model-30.1.0-javadoc.jar",
          "url": "lint-model-30.1.0-javadoc.jar",
          "size": 261,
          "sha512": "ad01d598e8fbf2f2e4aa78b24b5cf231960bcb28c584249a2927b44b4f99740c3c34d21f71a508ad6b7dea8ab573e57dddd48f6f64ea85ae0c5000813c93980e",
          "sha256": "52f39254967aaf1f5d48f8add25a14f62001c34ae5b5e59cef56ef36386cfdaa",
          "sha1": "615e0c47b5962087ee34a6a2007c1a4b456f2056",
          "md5": "7611a8b960b0013597d2899cb349781c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-model-30.1.0-sources.jar",
          "url": "lint-model-30.1.0-sources.jar",
          "size": 39593,
          "sha512": "b8d0f522631ea2d815d8b7d4577c3925b7390643f1f585e16c109bbfd9fa5fc505d9fe2ec93978b278bb2a42fe52e0aeb9e35db9d3b6ee77e2f18a6ae7c579df",
          "sha256": "a632d7d97a80a0f1ec51598b290e7b145cd20f37bd2856dc09bfc2fa470989f0",
          "sha1": "1b40561c6f9b62383eb023e801e9ed7eae5c8133",
          "md5": "b0ea84398e16e9b66b30355f7c1b07dc"
        }
      ]
    }
  ]
}
