{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-1.0.0.aar",
          "url": "emoji2-1.0.0.aar",
          "size": 129432,
          "sha512": "707e2a625be58ef95573982e26b74118b90bc36e1a1433606b894f69028e915be2f8616b445ad9d260eb5fe10fe2ed48a498d394e953b84b866526891ff9cb8e",
          "sha256": "af075731a4d17beaa29e69194a6baaf5f3512814c19aa1b8965d1920b0b7fbfa",
          "sha1": "4983c8c72474a8db5731df0c36fc701130bdb6e0",
          "md5": "c986ec6bc32069d575f97f12339777de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-1.0.0.aar",
          "url": "emoji2-1.0.0.aar",
          "size": 129432,
          "sha512": "707e2a625be58ef95573982e26b74118b90bc36e1a1433606b894f69028e915be2f8616b445ad9d260eb5fe10fe2ed48a498d394e953b84b866526891ff9cb8e",
          "sha256": "af075731a4d17beaa29e69194a6baaf5f3512814c19aa1b8965d1920b0b7fbfa",
          "sha1": "4983c8c72474a8db5731df0c36fc701130bdb6e0",
          "md5": "c986ec6bc32069d575f97f12339777de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji2-1.0.0-sources.jar",
          "url": "emoji2-1.0.0-sources.jar",
          "size": 48497,
          "sha512": "dd88f2ab3537da85c3e461940780c2bad1a486410a4b5aeb2fa5ae3b84628a4dbd777473a2624ca612c40a1bccc9ca455330fb25be435851821cf2d91752fb34",
          "sha256": "81eb9c1cc2095ac9579ef697d9af16f7fb5a033f00b7f806d47a4b70fc2fb3fb",
          "sha1": "84437bb39e1d32ddd2cab288beb90177913dcb99",
          "md5": "104d74fb488550fec0f79b2b327e1514"
        }
      ]
    }
  ]
}
