{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "7.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.1.0.jar",
          "url": "gradle-api-7.1.0.jar",
          "size": 234299,
          "sha512": "dda673494d5d70802f0001d5899ee8ec61c799609bc7c12ce39f0a7f2c45cc2bac828c8d4d9e558086a7ef3b5fa7aded094304bce3acb0d6ad7b3954d7dc6d1f",
          "sha256": "9c5ed0e13a6e8b426341cd32dcab2dd5b54c52e701a135b4227ccfe8ef3266bf",
          "sha1": "7c3f3ebe42be5c68ee64422a4db719732e06d7a8",
          "md5": "2733eeeef478f543eb9e17b723089c28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.1.0.jar",
          "url": "gradle-api-7.1.0.jar",
          "size": 234299,
          "sha512": "dda673494d5d70802f0001d5899ee8ec61c799609bc7c12ce39f0a7f2c45cc2bac828c8d4d9e558086a7ef3b5fa7aded094304bce3acb0d6ad7b3954d7dc6d1f",
          "sha256": "9c5ed0e13a6e8b426341cd32dcab2dd5b54c52e701a135b4227ccfe8ef3266bf",
          "sha1": "7c3f3ebe42be5c68ee64422a4db719732e06d7a8",
          "md5": "2733eeeef478f543eb9e17b723089c28"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.1.0-javadoc.jar",
          "url": "gradle-api-7.1.0-javadoc.jar",
          "size": 464814,
          "sha512": "dac1a8d322d31d5875a557b87aed69ed6a16c1aeda3726213336e5fefd1d3e326f144afda3040530935b2b890a4286d260c01843c6e3e910e5f6e66fca080348",
          "sha256": "7dd884177ec4797c83a984a5d715ba9a586c958b3c176fefa237c5fd62cf0a0d",
          "sha1": "b2f6c2177069b689f5fbebe1eaae14220405bfbf",
          "md5": "45682518cd6961eaa303849e7a5c2857"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.1.0-sources.jar",
          "url": "gradle-api-7.1.0-sources.jar",
          "size": 235381,
          "sha512": "ac4a6dc091d651a0731838e7fb504f1e7c8594a6ed3eb17e9979c31913c9900c052891b67b4c817b8224168250902dca257f2791889b06945b82dba9e6b44979",
          "sha256": "0f21b49c44e2a309aab42cd274b2231496b4bede5d977de27190e5ae7e175cfd",
          "sha1": "c7da89925561ed5cf3309976980e1d332bd9db77",
          "md5": "ba1731d94b0fffd4e60a9effb5eb698c"
        }
      ]
    }
  ]
}
