{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.2.0-rc01.aar",
          "url": "savedstate-1.2.0-rc01.aar",
          "size": 19330,
          "sha512": "1fd8015eb0cb30fa51a36ae4dc9a1d8b9da8d681c85ba94a332841bd19db342e3128f1d03c5c3c0aa8777577b5752a48a669a4a19760810670925f75fd561884",
          "sha256": "b30d27965902dcad22c5c2309e57ea8ada065757b9170058551f69551cae5ecd",
          "sha1": "18251ee1de45fde9b59902c0e040ad2a3af4c133",
          "md5": "21bf5efb081db77547ea7f3f97fd4390"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.2.0-rc01.aar",
          "url": "savedstate-1.2.0-rc01.aar",
          "size": 19330,
          "sha512": "1fd8015eb0cb30fa51a36ae4dc9a1d8b9da8d681c85ba94a332841bd19db342e3128f1d03c5c3c0aa8777577b5752a48a669a4a19760810670925f75fd561884",
          "sha256": "b30d27965902dcad22c5c2309e57ea8ada065757b9170058551f69551cae5ecd",
          "sha1": "18251ee1de45fde9b59902c0e040ad2a3af4c133",
          "md5": "21bf5efb081db77547ea7f3f97fd4390"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "savedstate-1.2.0-rc01-sources.jar",
          "url": "savedstate-1.2.0-rc01-sources.jar",
          "size": 8863,
          "sha512": "e59da08967bc69c1387208fa2e0a11c98a53bf2b252540207da7915cce1a8e97d3073e3aa4f31a1b986e876bf6dbaedc38d963c5562242d24bc9d28a3c0b185a",
          "sha256": "27056b2a9cddc7e5dc73700771f4e8dddbbcbab52b6cb46e33edc9588337e1cd",
          "sha1": "fce79e03fd65c3734d1c9364244456d89d336810",
          "md5": "4216af3a5bd0fb4ab22b682db63c615c"
        }
      ]
    }
  ]
}