{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.4.0.aar",
          "url": "appcompat-1.4.0.aar",
          "size": 1118239,
          "sha512": "b39d1c44e12e425a61dd1dc88415cfabf44bf9f7e48806221f596aacc16b53e74c1af783ce1545b863f050481e9622efffdc4185fb99c09576c8ddfe0db04f92",
          "sha256": "c77d9161c19ed066e9968e0fbd010e27eba1303286f5f9a12b4aa399bfb5d8f8",
          "sha1": "8c305c4a0968eab587cbf7edd2df023c53bb1d3f",
          "md5": "6dd8c24115db109654b0d9b52630524e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.4.0.aar",
          "url": "appcompat-1.4.0.aar",
          "size": 1118239,
          "sha512": "b39d1c44e12e425a61dd1dc88415cfabf44bf9f7e48806221f596aacc16b53e74c1af783ce1545b863f050481e9622efffdc4185fb99c09576c8ddfe0db04f92",
          "sha256": "c77d9161c19ed066e9968e0fbd010e27eba1303286f5f9a12b4aa399bfb5d8f8",
          "sha1": "8c305c4a0968eab587cbf7edd2df023c53bb1d3f",
          "md5": "6dd8c24115db109654b0d9b52630524e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-1.4.0-sources.jar",
          "url": "appcompat-1.4.0-sources.jar",
          "size": 475673,
          "sha512": "6302f70f4c40e5c743d2ef5b61aa0119b136789adf44e512b66d215da8698b8df5c456843ea87c235de025d30d04f982df005fa866012f748ca368a6cf81d675",
          "sha256": "7e5a50cf9224e55b3b65d7646365fd15121b1682ae6e34df9717b6ab5db46c0a",
          "sha1": "90635e5c864748b479ea6bdd3439b68a6eb678a9",
          "md5": "7b24b40b60b22b7474cdad701a14a6f8"
        }
      ]
    }
  ]
}
