{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "apkzlib",
    "version": "7.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "apkzlib-7.1.0.jar",
          "url": "apkzlib-7.1.0.jar",
          "size": 202884,
          "sha512": "b78a71633a60191ef6361efa52bb7a0e25ead169e85cb3987cb55b58c58843f1acb110e48438d8e49e72258432c6a8e7a8cdb5d452a515bf553457399710c03d",
          "sha256": "0e46a02577de7cbad380679e565f73d537205e0c38c2894bfe122ad1ee79e516",
          "sha1": "1f75ff1c23972cf4f304927e5b50a8f333534b63",
          "md5": "389e44184663ba8d21a725669357135f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-7.1.0.jar",
          "url": "apkzlib-7.1.0.jar",
          "size": 202884,
          "sha512": "b78a71633a60191ef6361efa52bb7a0e25ead169e85cb3987cb55b58c58843f1acb110e48438d8e49e72258432c6a8e7a8cdb5d452a515bf553457399710c03d",
          "sha256": "0e46a02577de7cbad380679e565f73d537205e0c38c2894bfe122ad1ee79e516",
          "sha1": "1f75ff1c23972cf4f304927e5b50a8f333534b63",
          "md5": "389e44184663ba8d21a725669357135f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-7.1.0-javadoc.jar",
          "url": "apkzlib-7.1.0-javadoc.jar",
          "size": 699550,
          "sha512": "31e1c762f4187a77324fbba9a3fb0f076895bd69f441147edf1ed6a27007abf20bb4e17f81cf300b39cfdeac2cc1f23bcafccbcf0d2d25e9ea61d20f752f81a4",
          "sha256": "6fe9ab6268b11418609c7c58ff1053245d443bff68632667c37d2e95ecbd8c38",
          "sha1": "9baa9e6cc62ed328485e7a6158b49f929cd28ec2",
          "md5": "5509af243a987c44d2fa8ae619ec808d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-7.1.0-sources.jar",
          "url": "apkzlib-7.1.0-sources.jar",
          "size": 175862,
          "sha512": "aecaae44d438f0c1274fe9c747c40f62134c542062161aa9868cfbb17bc3fb933c8ed4ff2227846b9b56077c726ba2b4104cbb005d51182c3863b630fdf1f016",
          "sha256": "155c8746d0649300fd8e08366aaff3385f48f38e6a3516547c186e2abc61a6ab",
          "sha1": "12b718634cef6b682c95e9d91dcea45038e68932",
          "md5": "79c167e4a7598b5f0fbe1655c43b9ab1"
        }
      ]
    }
  ]
}
