{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-device-provider-gradle-proto",
    "version": "30.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-proto-30.1.0.jar",
          "url": "android-device-provider-gradle-proto-30.1.0.jar",
          "size": 38003,
          "sha512": "cfa604cde0290be7bf29e5ce3bf0ce1de7c1e0d2501aaa45a92388d48aefbb727f93321903f7ae0b85ab065c9ad7aca2a4d2e5c5687be872067fcf417beca56f",
          "sha256": "69e2ac4c1fabf7a96fb4587c7be25a83420cacae60d8b8007da9c30b9e25ed81",
          "sha1": "c07304f4c175d59aa1dc06c723835bcd6aae5f59",
          "md5": "3b8f0009ec99afbc45a2cff433f113f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-device-provider-gradle-proto-30.1.0.jar",
          "url": "android-device-provider-gradle-proto-30.1.0.jar",
          "size": 38003,
          "sha512": "cfa604cde0290be7bf29e5ce3bf0ce1de7c1e0d2501aaa45a92388d48aefbb727f93321903f7ae0b85ab065c9ad7aca2a4d2e5c5687be872067fcf417beca56f",
          "sha256": "69e2ac4c1fabf7a96fb4587c7be25a83420cacae60d8b8007da9c30b9e25ed81",
          "sha1": "c07304f4c175d59aa1dc06c723835bcd6aae5f59",
          "md5": "3b8f0009ec99afbc45a2cff433f113f4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-proto-30.1.0-javadoc.jar",
          "url": "android-device-provider-gradle-proto-30.1.0-javadoc.jar",
          "size": 444345,
          "sha512": "8692971a34b497d5a09baf86bf365a0cc773d4852fee91233361f37205b0a94e1e80d359122cf889f95e06fdc6aca19fcdd78b85b6b00ae04b114bf9c068313e",
          "sha256": "15331133b17a33134fd5da3dcdee0520824f7fa8b74ae35fb8f00545f29a461c",
          "sha1": "de1eaccd6ac0cc19219fd865a605b07832ed69a1",
          "md5": "f053a1c1010b382557e9ddd1153d97a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-proto-30.1.0-sources.jar",
          "url": "android-device-provider-gradle-proto-30.1.0-sources.jar",
          "size": 16990,
          "sha512": "64df760531e47f992b362556da33e33c7cab4ec633e9378025b84c1e6a0f292351a755dbceddebe8d0cdaeb7af4f4178acd605875ac161a605d9a1f152916926",
          "sha256": "e16235063da03b0431f0e947e16a5834331b8b317eab651598398e334e7fe506",
          "sha1": "5b07b6a0b318e4f8321d31050b73d3506666bbd0",
          "md5": "7ddade577b46547ba6cf32c463fd8533"
        }
      ]
    }
  ]
}
