{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.7.0.aar",
          "url": "core-1.7.0.aar",
          "size": 980200,
          "sha512": "d7669aa141fe04841561eb1ec5bd021f85ae16694faca4bebb3b9720c70abfd2d264eb9958e70915b5d16575ae205ed1476c8e1ac7a6234dde1866467557e832",
          "sha256": "aaf6734226fff923784f92f65d78a2984dbf17534138855c5ce2038f18656e0b",
          "sha1": "b26edc58f29ca0671e60828a68582760f880acdd",
          "md5": "ab4dd1d02718c9c2a30e84012eb29941"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.7.0.aar",
          "url": "core-1.7.0.aar",
          "size": 980200,
          "sha512": "d7669aa141fe04841561eb1ec5bd021f85ae16694faca4bebb3b9720c70abfd2d264eb9958e70915b5d16575ae205ed1476c8e1ac7a6234dde1866467557e832",
          "sha256": "aaf6734226fff923784f92f65d78a2984dbf17534138855c5ce2038f18656e0b",
          "sha1": "b26edc58f29ca0671e60828a68582760f880acdd",
          "md5": "ab4dd1d02718c9c2a30e84012eb29941"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.7.0-sources.jar",
          "url": "core-1.7.0-sources.jar",
          "size": 798483,
          "sha512": "b92889a38f604f52c1cc94ec0fe368e138244ac4715e9b13c464c980ec799b830c3e25140c395297c4d19970e9dcb6051d12b817f8c4306a4e1ff06a3e5a5111",
          "sha256": "5421e943026bafe2b43da3fe87eb64091dcdb40ad1ce2026d0014c1a0e86686c",
          "sha1": "f1c3685231d49092ae301932de1481d9b7a9e025",
          "md5": "8022c1253f3bb3991c593ccd0735dfff"
        }
      ]
    }
  ]
}
