{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "7.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "30.4.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-7.4.0.jar",
          "url": "builder-7.4.0.jar",
          "size": 10851966,
          "sha512": "11602e681f77fea23abcecd191fd92f4ca0ffe33444a5812fd98feacc1f0d25016cd55149b1cb794aac5280fdbc1bff8550df1b4511db883e2b2fabc98927ce2",
          "sha256": "73b740436137e27ef384e8b00bc82219f84c641b12e91a0124384b19f0e86b07",
          "sha1": "460ac3910a6387c80ebad2dbae6da984dcf2f536",
          "md5": "a0e503e38589f214f29a6c5dae45b5ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.4.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "30.4.0"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "30.4.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "30.4.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "30.4.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-7.4.0.jar",
          "url": "builder-7.4.0.jar",
          "size": 10851966,
          "sha512": "11602e681f77fea23abcecd191fd92f4ca0ffe33444a5812fd98feacc1f0d25016cd55149b1cb794aac5280fdbc1bff8550df1b4511db883e2b2fabc98927ce2",
          "sha256": "73b740436137e27ef384e8b00bc82219f84c641b12e91a0124384b19f0e86b07",
          "sha1": "460ac3910a6387c80ebad2dbae6da984dcf2f536",
          "md5": "a0e503e38589f214f29a6c5dae45b5ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-7.4.0-javadoc.jar",
          "url": "builder-7.4.0-javadoc.jar",
          "size": 724630,
          "sha512": "6e09575e15be4eef4c61124038edeb986eddbd5f83b432335ec41b50f023c3f60e83104c54b79669f10559b3297cf6ef31b7b37039bc47c8e5e6a37c973e3012",
          "sha256": "52d8a6932ddd26330b542e7a445f5a590fd2eea1779590f4baf97c6a316cb0e8",
          "sha1": "f15a6fd5aa65af657838413d9813116a044c7a4d",
          "md5": "960f58faa3c5c07934ac665157c74145"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-7.4.0-sources.jar",
          "url": "builder-7.4.0-sources.jar",
          "size": 279907,
          "sha512": "ae9046f7eb7bc615199b6fabdf6b9f3fca72f7a7de7b800a344b095599bcf5b92bedc7bdcd6e4069d2b151d5df19ed46d2de0ee3c5e7fd82cfdc13b85085f9ca",
          "sha256": "5ca4b69d8541e25b1db40f686ff41489fd6baa5c914715d0386537e4fe3636f6",
          "sha1": "e7a8555b1ab21668a37066229834f6f379cc6f4b",
          "md5": "711a52aa625a7125943e14979582a6d1"
        }
      ]
    }
  ]
}
